# Generated by Django 5.0.3 on 2024-04-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0005_apartmentphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='description_ar',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='title_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
    ]
