# Generated by Django 5.0.3 on 2024-03-28 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_address_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birth_governorate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
