# Generated by Django 5.0.3 on 2024-04-03 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='national_id',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='National ID must be exactly 14 digits long.', regex='^\\d{14}$')], verbose_name='national ID'),
        ),
    ]
