# Generated by Django 5.0.3 on 2024-04-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customuser_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='is_verified'),
        ),
    ]
